Repository wpengine/wp-graphql-content-blocks, pull requests merged in 2024-09, with the labels that each got.

#269 ci: skip Sonar Qube workflow if PR is opened from a non org member
  .changeset/five-turtles-rule.md
  .github/workflows/sonar.yml
Labels: scope: build scripts

#271 chore: test against WP 6.6
  .changeset/light-frogs-grow.md
  .github/workflows/test-plugin-nightly.yml
  .github/workflows/test-plugin.yml
  docker-compose.yml
  readme.txt
Labels: scope: build scripts, scope: tests, type: chore

#272 chore: fix non-code phpstan errors
  .changeset/late-poems-study.md
  includes/updates/update-callbacks.php
  phpstan-baseline.neon
  phpstan/constants.php
Labels: scope: code quality, type: chore

#262 fix: check if `get_current_screen()` is set before accessing properties
  .changeset/green-cows-accept.md
  includes/updates/update-callbacks.php
  phpstan-baseline.neon
Labels: type: bug
